### ISSUE TITLE
font

### ISSUE THREAD

**Issue by eyadsibai** [zakariaGatter/i3blocks-gate#1]
which font r u using to get the output same as in the images

**Comment by zakariaGatter** [comment]
Terminus Font 
**Ubuntu**  : `sudo apt install xfont-terminus` 

Thnx for using my scripts and dont forget to star my work

**Comment by eyadsibai** [comment]
thanks a lot! ... I am using arch linux ... but the terminus is different there!

**Comment by eyadsibai** [comment]
I think it is a different font ... could u confirm?

**Comment by zakariaGatter** [comment]
```
bar {
      font pango:Terminus, FontAwesome 8
}
```

**Comment by eyadsibai** [comment]
Thanks!
