### ISSUE TITLE
Could not parse JSON

### ISSUE THREAD

**Issue by fabiocruzcoelho** [zakariaGatter/i3blocks-gate#4]
Hi, I'm using your script to set up my i3bloks but I'm getting the following error.

Error: Could not parse JSON (lexical error: invalid character inside string

Do I need to install anything else?

**Comment by zakariaGatter** [comment]
Thank u for using i3block-gate scripts 
Can u show me the i3 and i3blocks config files

**Comment by fcruzcoelho** [comment]
> Thank u for using i3block-gate scripts
> Can u show me the i3 and i3blocks config files

yes
i3blocks.conf
cat ~/.config/i3/i3blocks.conf
[Bat]
command=~/.config/i3blocks/Blocks/Ubuntu/blocks.sh [6]
interval=5
color=#XXXXXX

i3-config
cat ~/.config/i3/config 
set $mod Mod4

# Font for window titles
font pango: System San Francisco Display 9

# color
set $bg-color 	         #2f343f
set $inactive-bg-color   #4b5162
set $text-color          #f3f4f5
set $inactive-text-color #f3f4f5
set $urgent-bg-color     #E53935

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec terminator

# kill focused window
bindsym $mod+q kill

# start rofi (a program launcher)
bindsym $mod+d exec rofi -show run -lines 10 -eh 1.3 -opacity "90" -bw 0 -font "System San Francisco Display 10"

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+ccedilla focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
bindsym $mod+Tab 	workspace next
bindsym $mod+Shift+Tab  workspace prev

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+ccedilla move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

# reload the configuration file
bindsym $mod+Shift+c reload

# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart

# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym ccedilla resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
	#status_command i3status
    status_command i3blocks -c ~/.config/i3/i3blocks.conf
	font pango:DejaVu Sans Mono 10
    mode hide
	#position top
        colors {
		background 	#000000
        	separator #757575	
        	#                  border             background         text
		focused_workspace  $bg-color          $inactive-bg-color $text-color
		inactive_workspace $bg-color          $bg-color          $inactive-text-color
		urgent_workspace   $urgent-bg-color   $urgent-bg-color   $text-color
	}
}

#border
new_window  pixel  1

# Move to workspace
#assign [instance="spotify|slack"] $ws2

# floating
for_window [class="Pavucontrol"] floating enable

# window colors
#                       border              background         text                 indicator
client.focused          $bg-color           $bg-color          $text-color          $text-color
client.unfocused        $inactive-bg-color  $inactive-bg-color $inactive-text-color $inactive-bg-color
client.focused_inactive $inactive-bg-color  $inactive-bg-color $inactive-text-color $inactive-bg-color
client.urgent           $urgent-bg-color    $urgent-bg-color   $text-color          $urgent-bg-color

# Autostart
exec --no-startup-id compton -b --config ~/.config/i3/compton.conf
exec --no-startup-id nitrogen --restore
exec --no-startup-id nm-applet
exec --no-startup-id volumeicon
exec --no-startup-id betterlockscreen -w dim
exec_always --no-startup-id numlockx on

# Shortcut apps
bindsym $mod+shift+x exec betterlockscreen -l dim
bindsym $mod+F2 exec google-chrome
bindsym $mod+F3 exec spotify
bindsym $mod+Shift+s exec pavucontrol

# Auto
workspace_auto_back_and_forth yes

**Comment by fabiocruzcoelho** [comment]
> Thank u for using i3block-gate scripts
> Can u show me the i3 and i3blocks config files

i3bloks.conf
cat ~/.config/i3/i3blocks.conf
```
[Bat]
command=~/.config/i3blocks/Blocks/Ubuntu/blocks.sh [6]
interval=5
color=#XXXXXX
```

------
i3-confg
cat ~/.config/i3/config 
```
set $mod Mod4

# Font for window titles
font pango: System San Francisco Display 9

# color
set $bg-color 	         #2f343f
set $inactive-bg-color   #4b5162
set $text-color          #f3f4f5
set $inactive-text-color #f3f4f5
set $urgent-bg-color     #E53935

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec terminator

# kill focused window
bindsym $mod+q kill

# start rofi (a program launcher)
bindsym $mod+d exec rofi -show run -lines 10 -eh 1.3 -opacity "90" -bw 0 -font "System San Francisco Display 10"

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+ccedilla focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
bindsym $mod+Tab 	workspace next
bindsym $mod+Shift+Tab  workspace prev

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+ccedilla move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

# reload the configuration file
bindsym $mod+Shift+c reload

# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart

# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym ccedilla resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
	#status_command i3status
    status_command i3blocks -c ~/.config/i3/i3blocks.conf
	font pango:DejaVu Sans Mono 10
    mode hide
	#position top
        colors {
		background 	#000000
        	separator #757575	
        	#                  border             background         text
		focused_workspace  $bg-color          $inactive-bg-color $text-color
		inactive_workspace $bg-color          $bg-color          $inactive-text-color
		urgent_workspace   $urgent-bg-color   $urgent-bg-color   $text-color
	}
}

#border
new_window  pixel  1

# Move to workspace
#assign [instance="spotify|slack"] $ws2

# floating
for_window [class="Pavucontrol"] floating enable

# window colors
#                       border              background         text                 indicator
client.focused          $bg-color           $bg-color          $text-color          $text-color
client.unfocused        $inactive-bg-color  $inactive-bg-color $inactive-text-color $inactive-bg-color
client.focused_inactive $inactive-bg-color  $inactive-bg-color $inactive-text-color $inactive-bg-color
client.urgent           $urgent-bg-color    $urgent-bg-color   $text-color          $urgent-bg-color

# Autostart
exec --no-startup-id compton -b --config ~/.config/i3/compton.conf
exec --no-startup-id nitrogen --restore
exec --no-startup-id nm-applet
exec --no-startup-id volumeicon
exec --no-startup-id betterlockscreen -w dim
exec_always --no-startup-id numlockx on

# Shortcut apps
bindsym $mod+shift+x exec betterlockscreen -l dim
bindsym $mod+F2 exec google-chrome
bindsym $mod+F3 exec spotify
bindsym $mod+Shift+s exec pavucontrol

# Auto
workspace_auto_back_and_forth yes
```

**Comment by zakariaGatter** [comment]
Change in i3blocks config 
```
[Bat]
command=~/.config/i3blocks/Blocks/Ubuntu/blocks.sh 6
interval=5
color=#FFFFFF
```

change in i3 config file : 
font pango:DejaVu Sans Mono 10, FontAwesome 10

and try to install those application
```fonts-font-awesome lm-senser alsa-utils acpi xdotool sysstat suckless-tools```

**Comment by fabiocruzcoelho** [comment]
> Change in i3blocks config
> 
> ```
> [Bat]
> command=~/.config/i3blocks/Blocks/Ubuntu/blocks.sh 6
> interval=5
> color=#FFFFFF
> ```
> change in i3 config file :
> font pango:DejaVu Sans Mono 10, FontAwesome 10
> 
> and try to install those application
> `fonts-font-awesome lm-senser alsa-utils acpi xdotool sysstat suckless-tools`

Hello,

I made the config as informed but the problem still could show me how is yours?

the problem is the "[" when I take the error add but the icon does not appear with the parameter that I pass for eg the battery.

when I run ./blocks.sh 6 it shows the percentage of the battery normally.

Do you know what it can be?

Thank you

**Comment by fabiocruzcoelho** [comment]
it worked, thank you

**Comment by zakariaGatter** [comment]
you welcome
